# Generated by Django 4.2.7 on 2024-04-26 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clubs',
            fields=[
                ('clubname', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('clubtype', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=200, null=True)),
                ('rules', models.CharField(max_length=200)),
                ('adminname', models.CharField(max_length=100)),
                ('imagee', models.ImageField(null=True, upload_to='fimage')),
            ],
            options={
                'db_table': 'club',
            },
        ),
        migrations.CreateModel(
            name='conversations',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pkk', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'conversations',
            },
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('stu_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=300)),
                ('lastName', models.CharField(max_length=260)),
                ('password', models.CharField(max_length=300)),
                ('batch', models.CharField(max_length=10)),
                ('dept', models.CharField(max_length=200)),
                ('phone_number', models.CharField(default='', max_length=12)),
                ('active', models.CharField(default='false', max_length=20)),
                ('profpic', models.ImageField(null=True, upload_to='images')),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='posts',
            fields=[
                ('text', models.CharField(max_length=10000)),
                ('upvote', models.CharField(default='0', max_length=100, null=True)),
                ('category', models.CharField(max_length=100)),
                ('iid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('pictures', models.ImageField(null=True, upload_to='posts')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metamesh.students')),
            ],
            options={
                'db_table': 'posts',
            },
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='', max_length=200)),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metamesh.students')),
            ],
            options={
                'db_table': 'notification',
            },
        ),
        migrations.CreateModel(
            name='messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(default='', max_length=300, null=True)),
                ('convs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metamesh.conversations')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metamesh.students')),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='eevent',
            fields=[
                ('bannerImg', models.ImageField(blank=True, default='', upload_to='banner')),
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('cat', models.CharField(max_length=100)),
                ('stime', models.CharField(max_length=20)),
                ('etime', models.CharField(max_length=30)),
                ('details', models.CharField(max_length=400)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metamesh.students')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metamesh.clubs')),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.AddField(
            model_name='conversations',
            name='userss',
            field=models.ManyToManyField(to='metamesh.students'),
        ),
        migrations.AddField(
            model_name='clubs',
            name='adminid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metamesh.students'),
        ),
        migrations.CreateModel(
            name='clubpost',
            fields=[
                ('texts', models.CharField(default='', max_length=300)),
                ('iid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('upvote', models.CharField(default='0', max_length=200, null=True)),
                ('cimage', models.ImageField(null=True, upload_to='cposts')),
                ('clubidd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metamesh.clubs')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metamesh.students')),
            ],
            options={
                'db_table': 'clubpost',
            },
        ),
        migrations.CreateModel(
            name='clublikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.CharField(default='0', max_length=100, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metamesh.clubs')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metamesh.clubpost')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metamesh.students')),
            ],
            options={
                'db_table': 'clublikes',
            },
        ),
        migrations.CreateModel(
            name='likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.CharField(default='0', max_length=100, null=True)),
                ('comment', models.CharField(max_length=250, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metamesh.posts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metamesh.students')),
            ],
            options={
                'db_table': 'like',
                'unique_together': {('post', 'user')},
            },
        ),
        migrations.CreateModel(
            name='clubApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='not', max_length=100)),
                ('admin', models.CharField(default='', max_length=100)),
                ('clubid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metamesh.clubs')),
                ('studentss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metamesh.students')),
            ],
            options={
                'db_table': 'approval',
                'unique_together': {('clubid', 'studentss')},
            },
        ),
    ]
